name: Build and Deploy RFP Radar

on:
  push:
    branches:
      - main
      - dev-v3
      - demo-v3
      - hotfix
    paths:
      - 'src/rfp_radar/**'
      - '.github/workflows/rfp-radar-deploy.yml'
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
    branches:
      - main
      - dev-v3
      - demo-v3
      - hotfix
    paths:
      - 'src/rfp_radar/**'
      - '.github/workflows/rfp-radar-deploy.yml'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure Container Registry
        if: ${{ github.ref_name == 'main' || github.ref_name == 'dev-v3'|| github.ref_name == 'demo-v3' || github.ref_name == 'hotfix' }}
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER || 'acrlogin.azurecr.io' }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Get registry
        id: registry
        run: |
          echo "ext_registry=${{ secrets.ACR_LOGIN_SERVER || 'acrlogin.azurecr.io'}}" >> $GITHUB_OUTPUT

      - name: Determine Tag Name Based on Branch
        id: determine_tag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "TAG=latest_v3" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/dev-v3" ]]; then
            echo "TAG=dev_v3" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/demo-v3" ]]; then
            echo "TAG=demo_v3" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/hotfix" ]]; then
            echo "TAG=hotfix" >> $GITHUB_ENV
          else
            echo "TAG=pullrequest-ignore" >> $GITHUB_ENV
          fi

      - name: Set Historical Tag
        run: |
          DATE_TAG=$(date +'%Y-%m-%d')
          RUN_ID=${{ github.run_number }}
          # Create historical tag using TAG, DATE_TAG, and RUN_ID
          echo "HISTORICAL_TAG=${{ env.TAG }}_${DATE_TAG}_${RUN_ID}" >> $GITHUB_ENV

      - name: Build and optionally push RFP Radar Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./src/rfp_radar
          file: ./src/rfp_radar/Dockerfile
          push: ${{ env.TAG != 'pullrequest-ignore' }}
          tags: |
            ${{ steps.registry.outputs.ext_registry }}/macaerfpradar:${{ env.TAG }}
            ${{ steps.registry.outputs.ext_registry }}/macaerfpradar:${{ env.HISTORICAL_TAG }}
